services:
  - type: web
    name: crm-ecommerce-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CRM_DB_NAME
        value: crm
      - key: ECOMMERCE_DB_NAME
        value: ecommerce
      - key: ALLOWED_ORIGINS
        value: "*"
    healthCheckPath: /
    autoDeploy: true 